const artData = {
  art1: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  art2: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic2.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  art3: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic2.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  art4: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  art5: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic2.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  art6: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic2.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  art7: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  art8: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  art9: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic2.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  art10: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  art11: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  art12: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  art13: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  art14: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  art15: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic2.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  art16: {
    artName: "Starry Night",
    medium: "Oil on canvas",
    artist: "Vincent van Gogh",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "/artpic2.png",
    description: "A famous painting by Vincent van Gogh.",
  },
  
};

export default artData;
