const artData = {
  art1: {
    artName: "Mustang",
    medium: "Photoshop",
    artist: "Utsav Thakur",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/thakur_utsav_" ,
    linkedin : "https://www.linkedin.com/in/utsav-thakur-960760294?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=1Av-_8J74OjqNEhVIBLYPzt284FKqXxi0",
    description: "The all classic , everyone's favourite , FORD MUSTANG SHELBY 350",
    
  },
  art2: {
    artName: "Abraham Lincoln",
    medium: "Photoshop",
    artist: "Rai Chirag Kumar",
    artistImage : "https://drive.google.com/open?id=1rfKVcV5auTXzzpS1WdE1Xlds-bBtpzQX",
    instagram : "https://www.instagram.com/chirag.rai31?igsh=MXJkZ2t3cXdlcXloNw==" ,
    linkedin : "https://www.linkedin.com/in/chirag-kumar-rai-bbb009271?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=164r6g-GmGHYNezkGpPgy9vDGSH_fXOq_",
    description: "Smokin' good Digital Portrait of The Abraham Lincoln",
  
  },
  art3: {
    artName: "Twirly Heart",
    medium: "Quiling",
    artist: "Anshu Kumari",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/anshukumari?igsh=MWlybmVsejh1Z3d5NA==" ,
    linkedin : "https://www.linkedin.com/in/anshu-kumari-a32936257?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=1jjAcwKXIhzvMZOmKPNHFG33qO5gXPHwC",
    description: "Beautiful , Colorful and Crafty Quilled Heart",
   
  },
  art4: {
    artName: "Bathing Bliss",
    medium: "Charcoal Shading",
    artist: "Saim Jawed",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/s._aim_jawed" ,
    linkedin : "https://www.linkedin.com/in/saim-jawed-6a8766294" ,
    artImage: "https://drive.google.com/uc?export=view&id=1vKWpdWssKvxfIfz1hJBnLNKw6nTVlyAk",
    description: "A little boy exploring the joy of bath on a sunny day",
  },
  art5: {
    artName: "Money Talks",
    medium: "Photoshop",
    artist: "Rai Chirag Kumar",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/chirag.rai31?igsh=MXJkZ2t3cXdlcXloNw==" ,
    linkedin : "https://www.linkedin.com/in/chirag-kumar-rai-bbb009271?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"  ,
    artImage: "https://drive.google.com/uc?export=view&id=1ZRSSD0YMpWUnMIJ0_yRj9Y3hbLo6KnRd",
    description: "The JACK of all trades , Leonardo DiCaprio",
    
  },
  art6: {
    artName: "The Might of the Mighty",
    medium: "Charcoal Shading",
    artist: "Saim Jawed",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/s._aim_jawed" ,
    linkedin : "https://www.linkedin.com/in/saim-jawed-6a8766294" ,
    artImage: "https://drive.google.com/uc?export=view&id=181Tl2GlPsvbYggrVK9iL1hAViE9fZOEl",
    description: "An african elephant roaming in the Savannah's",
    
  },
  art7: {
    artName: "Dino",
    medium: "Origami",
    artist: "Dipesh Kumar Singh",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/di.pesh279?igsh=MTV2c2x1Njdud3FpaA==" ,
    linkedin : "https://www.linkedin.com/in/dipesh-singh-0225891ba?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=12LmgM5EfGAhzHquCXI16bNBLvySn7I7A",
    description: "A Giraffe, a dragon. Ohh wait ! it's a dino. \n An amazing Origami of a dinoaur. ",
  },
  art8: {
    artName: "Bajrangbali",
    medium: "Pencil Shading",
    artist: "Gaurav Suman",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/gaurav.33_" ,
    linkedin : "https://www.linkedin.com/in/gaurav-suman-baa84328a" ,
    artImage: "https://drive.google.com/uc?export=view&id=1tz1DxK4AfICDdEVAQ8cg0Igpv0gopR7b",
    description: "The Lord Hanuman",
  },
  art9: {
    artName: "Daisies",
    medium: "Acrylic",
    artist: "Madhumista",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/jfoyrangggg" ,
    linkedin : "" ,
    artImage: "https://drive.google.com/uc?export=view&id=1PC3K6h1O10L9eRnWFRnM6jHbA8s1npLl",
    description: "A beautiful field of white daisies",
  },
  art10: {
    artName: "Ganesh",
    medium: "Pencil Shading",
    artist: "Nicky Kumari",
    artistImage : "/p1.jpeg",
    instagram: "https://www.instagram.com/nickyk2004?igsh=Z2tyaXhxNTkzeHE2",
    linkedin : " https://www.linkedin.com/in/nicky-kumari-7a57312b6?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=11d19CvvKSNBhjXs5Pe8QywPPSfhJX00e",
    description: "The Lord Ganesh",
   
    
  },
  art11: {
    artName: "Evening in Blue",
    medium: "Acrylic",
    artist: "Madhumista",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/jfoyrangggg" ,
    linkedin : "" ,
    artImage: "https://drive.google.com/uc?export=view&id=1G4weGuoWBR8JKWtXq-xANSoCuNd1wbAh",
    description: "A starry evening in blue",
  },
  art12: {
    artName: "MoonTracks",
    medium: "Watercolors",
    artist: "Supriya",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/supriya_sharma_568" ,
    linkedin : "https://www.linkedin.com/in/supriya-kumari-1021a7258?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=1heDDeheg01tjxQjv4NnxO_BvWBG7yA3O",
    description: "The mesmerizing scenery of a track bathed in the blissful moonlight",
   
  },
  art13: {
    artName: "Dripped in Shadows",
    medium: "Charcoal Shading",
    artist: "Saim Jawed",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/s._aim_jawed" ,
    linkedin : "https://www.linkedin.com/in/saim-jawed-6a8766294"  ,
    artImage: "https://drive.google.com/uc?export=view&id=1LLgkdR48d6sbKsYzDNV0fyxwNkI6DVvX",
    description: "A breathtaking sketch of a model while oil is dripping from her face.",
    
  },
  art14: {
    artName: "Floral Girl",
    medium: "Pencil Color",
    artist: "Damini Kumari",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/da_snowmin" ,
    linkedin : "https://www.linkedin.com/in/damini-kumari-a0a098282?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=1VBEho5xA5Bkojdz7EPdSWMZH4zK5yrs8",
    description: "A beautiful and colorful portrait of a young girl with flowers embedded in her hair.",
  },
  art15: {
    artName: "Nature's Symphony",
    medium: "Charcoal Shading",
    artist: "Saim Jawed",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/s._aim_jawed" ,
    linkedin : "https://www.linkedin.com/in/saim-jawed-6a8766294" ,
    artImage: "https://drive.google.com/uc?export=view&id=1YTxIXT-_8vEa7nTYDv8w1Rxqu8j9H1ZY",
    description: "A true combination of all of nature's beautiful aspects. Flowers, Birds, Animals, Humans all merged in a single frame."
  },
  art16: {
    artName: "Blossom",
    medium: "Quilling",
    artist: "Anshu Kumari",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/anshukumari?igsh=MWlybmVsejh1Z3d5NA==" ,
    linkedin : "https://www.linkedin.com/in/anshu-kumari-a32936257?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=1gMF2oH33FbQR5EYi2y-h2JUZOGPWxlvN",
    description: "A really vibrant mesh of colorful twirls forming a beautiful bouquet of flowers.",
  },
  art17: {
    artName: "Lady With Oranges",
    medium: "Acrylics",
    artist: "Bhavya Sinha",
    artistImage : "https://drive.google.com/open?id=1rfKVcV5auTXzzpS1WdE1Xlds-bBtpzQX",
    instagram : "https://www.instagram.com/bhav_yeaaah" ,
    linkedin : "https://www.linkedin.com/in/bhavya-sinha-?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=1fe37Em_MmMjo52dtprhV90GSlyYSDdKm",
    description: "A gorgeous Desi Lady holding an utensil full of oranges and grapes.",
  },
  art18: {
    artName: "Laxmi Ma",
    medium: "Digital",
    artist: "Bhavya Sinha",
    artistImage : "/p1.jpeg",
    iinstagram : "https://www.instagram.com/bhav_yeaaah" ,
    linkedin : "https://www.linkedin.com/in/bhavya-sinha-?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=1-vtaYGGt_e9mdsqJdLqfXemcMa5rP-Nd",
    description: "The Goddess of Wealth, Laxmi Ma",
  },
  art19 : {
    artName: "Mahadev",
    medium: "Pencil Shading",
    artist: "Gaurav Suman",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/gaurav.33_" ,
    linkedin : "https://www.linkedin.com/in/gaurav-suman-baa84328a" ,
    artImage: "https://drive.google.com/uc?export=view&id=1BBJjIWVfvnU-pujaxsQW1rPaowskO47b",
    description: "The Lord Shiva.",
  },
  art20: {
    artName: "Azim Premji",
    medium: "Ball Pen",
    artist: "Dipesh Kumar Singh",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/di.pesh279?igsh=MTV2c2x1Njdud3FpaA==" ,
    linkedin : "https://www.linkedin.com/in/dipesh-singh-0225891ba?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=19zKLGUq8wpKJ1OAaBGhN6dkbnqFyYMrO",
    description: "An amazing portrait of Sir Azim Premji in blue point ball pen.",
  },
  art21: {
    artName: "Eyes",
    medium: "Pencil Shading",
    artist: "Gaurav Suman",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/gaurav.33_" ,
    linkedin : "https://www.linkedin.com/in/gaurav-suman-baa84328a" ,
    artImage: "https://drive.google.com/uc?export=view&id=17-QMVYCnJYHXljAFNMMtGG_pZbMqDyBj",
    description: "A magnificent sketch of an elegant side eye look.",
  },
  art22: {
    artName: "NIT Patna",
    medium: "Digital",
    artist: "Sanya Pundhir",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "https://drive.google.com/uc?export=view&id=1Sm8ajkVm_RBMyZQNi9sxFAr_a35GGdD6",
    description: "A panoramic view of our Institute , NIT Patna.",
   
  },
  art23: {
    artName: "Drowsing Girl",
    medium: "Water Color",
    artist: "Damini Kumari",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/da_snowmin" ,
    linkedin : "https://www.linkedin.com/in/damini-kumari-a0a098282?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=1xezkh6iY25VwuY_U4foAjcyV4X0boJQD",
    description: "A relaxing painting of a girl catering herself to deep sleep.",
    
  },
  art24: {
    artName: "Peacock",
    medium: "Mandala Art",
    artist: "Moupiya Goldar",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/Its_mou2022piya" ,
    linkedin : "" ,
    artImage: "https://drive.google.com/uc?export=view&id=1Cu-6SogSfg_WLvuljPw71oN_ECl16ots",
    description: "A picturesque mandala art of a peacock.",
  },
  art25: {
    artName: "Radha Krishna",
    medium: "Acrylics",
    artist: "Sanya Pundhir",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "https://drive.google.com/uc?export=view&id=1XYCj0PV4dIVo97OzzbcOUdlmX34JLckB",
    description: "A captivating Madhubani painting of Radha Krishna.",
  },
  art26: {
    artName: "Ram Ji",
    medium: "Digital",
    artist: "Bhavya Sinha",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/bhav_yeaaah" ,
    linkedin : "https://www.linkedin.com/in/bhavya-sinha-?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=13fKjFhxoHCQAF_u9iG7cdy1kq6BJ4ZBS",
    description: "The Lord Ram.",
  },
  art27: {
    artName: "Ram Ji",
    medium: "Digital",
    artist: "Utsav Thakur",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/thakur_utsav_" ,
    linkedin : "https://www.linkedin.com/in/utsav-thakur-960760294?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=1GnXSEjy6XuGYnWrZl_ZlgB4dcpytEWUU",
    description: "The Lord Ram.",
  },
  art28: {
    artName: "Rural Beauty",
    medium: "Water Color",
    artist: "Damini Kumari",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/da_snowmin" ,
    linkedin : "https://www.linkedin.com/in/damini-kumari-a0a098282?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=1UKdwuCrrU2n0iWhVABsL4S3A7mHjELsY",
    description: "A graceful painting of a rural girl with her goat..",
  },
  art29: {
    artName: "Sadhu",
    medium: "Pencil Shading",
    artist: "Bhavya Sinha",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/bhav_yeaaah" ,
    linkedin : "https://www.linkedin.com/in/bhavya-sinha-?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=1hWNCH_ym5CJDF6VwDkqORzeb_tfG5XsN",
    description: "A Sadhu.",
  },
  art30: {
    artName: "Spongebob",
    medium: "Acrylic",
    artist: "Madhumista",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/jfoyrangggg" ,
    linkedin : "" ,
    artImage: "https://drive.google.com/uc?export=view&id=1d22J0cKPUwVmOifyD3NWuezCC0WHpiMZ",
    description: "Who else other than Mr. Squarepants, The Spongebob.",
  },
  art31: {
    artName: "Stare",
    medium: "Pencil Shading",
    artist: "Nicky Kumari",
    artistImage : "/p1.jpeg",
    instagram: "https://www.instagram.com/nickyk2004?igsh=Z2tyaXhxNTkzeHE2",
    linkedin : " https://www.linkedin.com/in/nicky-kumari-7a57312b6?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=1v4xXaqkUpzL8Tgf5jTx5wRQx7Bso7Gz0",
    description: "A sublime sketch of a girl in deep waters.",
  },
  art32: {
    artName: "Underwater",
    medium: "Acrylic",
    artist: "Sanya Pundhir",
    artistImage : "/p1.jpeg",
    instagram : "" ,
    linkedin : "" ,
    artImage: "https://drive.google.com/uc?export=view&id=18TImvM3TD1VPXDKKPOqL-GwHXPMZiAbQ",
    description: "A lovely painting of a girl swimming in blue ocean.",
  },
  art33: {
    artName: "Woman Hawking Fan",
    medium: "Poster Colors",
    artist: "Sanchita Jha",
    artistImage : "/p1.jpeg",
    instagram : "https://www.instagram.com/sanchitaj_04?igsh=MWF0anZucWRqY256cA==" ,
    linkedin : "https://www.linkedin.com/in/sanchita-jha?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" ,
    artImage: "https://drive.google.com/uc?export=view&id=1kWLo-cw5NMuO8WMpfS93MQILXVzPf3YE",
    description: "A beautiful Madhubani painting of a woman hawking a fan.",
  },
  
};

export default artData;
