const teamData = {
  events: {
  teamName: "Literary",
  teamImage: '/Pen.png',
  members: [
    { id: 1, name: 'Aniket Srivastav', position: 'Story writer', team: 'technical', image: '/p2.webp', branch: 'CSE-25', instagram: '',
    linkedin: '', twitter: '' },
    { id: 2, name: 'Arun singh', position: 'Shayri writing', team: 'technical', image: '/p1.jpeg', branch: 'CSE-25', instagram: '',
    linkedin: '', twitter: '' },
    { id: 2, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '/p2.webp', branch: 'CSE-26', instagram: '',
    linkedin: '', twitter: '' },
    { id: 4, name: 'Shradha Jha', position: 'Web developer', team: 'technical', image: '/p1.jpeg', branch: 'CSE-26', instagram: '',
    linkedin: '', twitter: '' },
    { id: 5, name: 'Satyam', position: 'Web developer', team: 'technical', image: '/p2.webp', branch: 'CSE-26', instagram: '',
    linkedin: '', twitter: '' },
    { id: 6, name: 'Nikhil Kumar Das', position: 'Web developer', team: 'technical', image: '/p1.jpeg', branch: 'CSE-26', instagram: '',
    linkedin: '', twitter: '' },
    { id: 7, name: 'Aditya Kumar', position: 'Web developer', team: 'technical', image: '/p2.webp', branch: 'ECEE-26', instagram: '',
    linkedin: '', twitter: '' },
    { id: 8, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '', branch: 'CSE-26', instagram: '',
    linkedin: '', twitter: '' },
  ],
},
event: {
  teamName: "Art",
  teamImage: '/ART.png',
  members: [
    { id: 1, name: 'Rohan Shetty', position: 'Face Painter', team: 'technical', image: '', branch: 'CSE-25', instagram: '',
    linkedin: '', twitter: '' },
    { id: 2, name: 'Arun Singh', position: 'Clay modelling', team: 'technical', image: '/p2.webp', branch: 'CSE-25', instagram: '',
    linkedin: '', twitter: '' },
    { id: 2, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '/p1.jpeg', branch: 'CSE-26', instagram: '',
    linkedin: '', twitter: '' },
    { id: 4, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '', branch: 'CSE-26', instagram: '',
    linkedin: '', twitter: '' },
    { id: 5, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '/p2.webp', branch: 'CSE-26', instagram: '',
    linkedin: '', twitter: '' },
    { id: 6, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '', branch: 'CSE-26', instagram: '',
    linkedin: '', twitter: '' },
    { id: 7, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '/p2.webp', branch: 'CSE-26', instagram: '',
    linkedin: '', twitter: '' },
    { id: 8, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '', branch: 'CSE-26', instagram: '',
    linkedin: '', twitter: '' },
  ],
},
technical: {
  teamName: "Technical",
  teamImage: '/developer.png',
  members: [
  { id: 1, name: 'Arun singh', position: 'Web developer', team: 'technical', image: '', branch: 'CSE-25', instagram: '',
  linkedin: '', twitter: '' },
  { id: 2, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '/p1.jpeg', branch: 'CSE-26', instagram: '',
  linkedin: '', twitter: '' },
  { id: 2, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '/p2.webp', branch: 'CSE-26', instagram: '',
  linkedin: '', twitter: '' },
  { id: 4, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '/p1.jpeg', branch: 'CSE-26', instagram: '',
  linkedin: '', twitter: '' },
  { id: 5, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '/p1.jpeg', branch: 'CSE-26', instagram: '',
  linkedin: '', twitter: '' },
  { id: 6, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '/p1.jpeg', branch: 'CSE-26', instagram: '',
  linkedin: '', twitter: '' },
  { id: 7, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '/p2.webp', branch: 'CSE-26', instagram: '',
  linkedin: '', twitter: '' },
  { id: 8, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '', branch: 'CSE-26', instagram: '',
  linkedin: '', twitter: '' },
],
},
nontechnical: {
  teamName: "Non-Technical",
  teamImage: '/Megaphone.png',
  members: [
  { id: 1, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '', branch: 'CSE-26', instagram: '',
  linkedin: '', twitter: '' },
  { id: 2, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '/p1.jpeg', branch: 'CSE-26', instagram: '',
  linkedin: '', twitter: '' },
  { id: 2, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '/p2.webp', branch: 'CSE-26', instagram: '',
  linkedin: '', twitter: '' },
  { id: 4, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '', branch: 'CSE-26', instagram: '',
  linkedin: '', twitter: '' },
  { id: 5, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '', branch: 'CSE-26', instagram: '',
  linkedin: '', twitter: '' },
  { id: 6, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '/p1.jpeg', branch: 'CSE-26', instagram: '',
  linkedin: '', twitter: '' },
  { id: 7, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '', branch: 'CSE-26', instagram: '',
  linkedin: '', twitter: '' },
  { id: 8, name: 'Shubham Tiwari', position: 'Web developer', team: 'technical', image: '', branch: 'CSE-26', instagram: '',
  linkedin: '', twitter: '' },
],
},
};

export default teamData;
